name: Split videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/sessions/**/*.json'

defaults:
  run:
    working-directory: packages/tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: sudo apt install -y nscd
      - run: yarn install
      - run: yarn split
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[av] split videos'
