name: Upload videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/sessions/**.mp4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: yarn install
      - run: yarn upload
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[new] upload videos'
